export class LayoutError extends Error {}
const finite=(name,value,min=null)=>{const n=Number(value);if(!Number.isFinite(n))throw new LayoutError(`${name} must be finite`);if(min!==null&&n<min)throw new LayoutError(`${name} must be >= ${min}`);return n};
const normalise=value=>Array.isArray(value)?value.map(normalise):(value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,normalise(value[key])])):value);
const canonical=value=>JSON.stringify(normalise(value));
const ROTR=(value,bits)=>(value>>>bits)|(value<<(32-bits));
const SHA256_K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
function sha256Hex(text){const bytes=new TextEncoder().encode(text),bitLength=bytes.length*8,paddedLength=Math.ceil((bytes.length+9)/64)*64,data=new Uint8Array(paddedLength);data.set(bytes);data[bytes.length]=0x80;const view=new DataView(data.buffer);view.setUint32(paddedLength-8,Math.floor(bitLength/0x100000000),false);view.setUint32(paddedLength-4,bitLength>>>0,false);const state=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19],words=new Uint32Array(64);for(let offset=0;offset<paddedLength;offset+=64){for(let i=0;i<16;i++)words[i]=view.getUint32(offset+i*4,false);for(let i=16;i<64;i++){const a=words[i-15],b=words[i-2],s0=(ROTR(a,7)^ROTR(a,18)^(a>>>3))>>>0,s1=(ROTR(b,17)^ROTR(b,19)^(b>>>10))>>>0;words[i]=(words[i-16]+s0+words[i-7]+s1)>>>0}let[a,b,c,d,e,f,g,h]=state;for(let i=0;i<64;i++){const S1=(ROTR(e,6)^ROTR(e,11)^ROTR(e,25))>>>0,ch=((e&f)^((~e)&g))>>>0,t1=(h+S1+ch+SHA256_K[i]+words[i])>>>0,S0=(ROTR(a,2)^ROTR(a,13)^ROTR(a,22))>>>0,maj=((a&b)^(a&c)^(b&c))>>>0,t2=(S0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}state[0]=(state[0]+a)>>>0;state[1]=(state[1]+b)>>>0;state[2]=(state[2]+c)>>>0;state[3]=(state[3]+d)>>>0;state[4]=(state[4]+e)>>>0;state[5]=(state[5]+f)>>>0;state[6]=(state[6]+g)>>>0;state[7]=(state[7]+h)>>>0}return state.map(value=>value.toString(16).padStart(8,'0')).join('')}
export const layoutHash=value=>`sha256:${sha256Hex(canonical(value))}`;
export function footprint(module){let rotation=((Number(module.rotation_deg)||0)%180+180)%180;if(![0,90].includes(rotation))throw new LayoutError('rotation must be 0 or 90 degrees');let width=finite('width_m',module.width_m,.001),height=finite('height_m',module.height_m,.001);if(rotation===90)[width,height]=[height,width];const x=finite('x_m',module.x_m),y=finite('y_m',module.y_m);return{left:x-width/2,right:x+width/2,bottom:y-height/2,top:y+height/2,width,height}}
export const intersects=(a,b)=>Math.min(a.right,b.right)>Math.max(a.left,b.left)&&Math.min(a.top,b.top)>Math.max(a.bottom,b.bottom);
const checkedBoundary=layout=>{const b=Object.fromEntries(['x_min','x_max','y_min','y_max'].map(k=>[k,finite(k,layout.boundary[k])]));if(b.x_max<=b.x_min||b.y_max<=b.y_min)throw new LayoutError('boundary must have positive width and height');return b};
const candidateErrors=(module,boundary,obstacles,existing)=>{const errors=[],fp=footprint(module);if(fp.left<boundary.x_min-1e-12||fp.right>boundary.x_max+1e-12||fp.bottom<boundary.y_min-1e-12||fp.top>boundary.y_max+1e-12)errors.push(`${module.id}: outside boundary`);for(const obstacle of obstacles){const of={left:finite('x_min',obstacle.x_min),right:finite('x_max',obstacle.x_max),bottom:finite('y_min',obstacle.y_min),top:finite('y_max',obstacle.y_max)};if(intersects(fp,of))errors.push(`${module.id}: intersects obstacle ${obstacle.id??'?'}`)}for(const [id,other] of existing)if(intersects(fp,other))errors.push(`${module.id}: overlaps ${id}`);return errors};
export function validateLayout(layout){const errors=[];let boundary;try{boundary=checkedBoundary(layout)}catch(error){return[error.message]}const modules=layout.modules||[],ids=modules.map(module=>module.id),obstacles=layout.obstacles||[],existing=[];if(new Set(ids).size!==ids.length)errors.push('module ids must be unique');for(const module of modules){try{errors.push(...candidateErrors(module,boundary,obstacles,existing));existing.push([module.id,footprint(module)])}catch(error){errors.push(`${module.id||'?'}: ${error.message}`)}}return errors}
const rehash=layout=>{const copy=structuredClone(layout);delete copy.layout_hash;layout.layout_hash=layoutHash(copy);return layout};
export function fillRectangle({boundary,moduleWidthM,moduleHeightM,gapXM=.02,gapYM=.02,orientation='portrait',staggerM=0,obstacles=[],limit=null}){if(!['portrait','landscape'].includes(orientation))throw new LayoutError('orientation must be portrait or landscape');const width=finite('moduleWidthM',moduleWidthM,.001),height=finite('moduleHeightM',moduleHeightM,.001),gapX=finite('gapXM',gapXM,0),gapY=finite('gapYM',gapYM,0),stagger=finite('staggerM',staggerM,0);if(limit!==null&&Number(limit)<0)throw new LayoutError('limit must be non-negative');const rotation=orientation==='landscape'?90:0,[footprintWidth,footprintHeight]=rotation===90?[height,width]:[width,height];const layout={schema_version:'globalgrid2050.v11.module-layout.v1',boundary:{...boundary},obstacles:structuredClone(obstacles),modules:[]},validBoundary=checkedBoundary(layout),accepted=[];let row=0;for(let y=validBoundary.y_min+footprintHeight/2;y+footprintHeight/2<=validBoundary.y_max+1e-12;y+=footprintHeight+gapY,row++){let column=0;for(let x=validBoundary.x_min+footprintWidth/2+(row%2?stagger:0);x+footprintWidth/2<=validBoundary.x_max+1e-12;x+=footprintWidth+gapX,column++){const module={id:`MOD-${String(layout.modules.length+1).padStart(4,'0')}`,x_m:+x.toFixed(9),y_m:+y.toFixed(9),width_m:width,height_m:height,rotation_deg:rotation,row,column,string_id:null};if(candidateErrors(module,validBoundary,layout.obstacles,accepted).length===0){layout.modules.push(module);accepted.push([module.id,footprint(module)]);if(limit!==null&&layout.modules.length>=Number(limit))return rehash(layout)}}}return rehash(layout)}
export function moveModule(layout,id,x,y,snap=.01){const result=structuredClone(layout),target=result.modules.find(module=>module.id===id);if(!target)throw new LayoutError(`unknown module ${id}`);const interval=finite('snap',snap,.000001);target.x_m=+(Math.round(finite('x',x)/interval)*interval).toFixed(9);target.y_m=+(Math.round(finite('y',y)/interval)*interval).toFixed(9);const errors=validateLayout(result);if(errors.length)throw new LayoutError(errors.join('; '));return rehash(result)}
export function rotateModule(layout,id){const result=structuredClone(layout),target=result.modules.find(module=>module.id===id);if(!target)throw new LayoutError(`unknown module ${id}`);target.rotation_deg=(Number(target.rotation_deg)||0)%180===0?90:0;const errors=validateLayout(result);if(errors.length)throw new LayoutError(errors.join('; '));return rehash(result)}
export function assignStrings(layout,size=30,snake=true){if(size<=0)throw new LayoutError('size must be positive');const result=structuredClone(layout),rows=new Map;for(const module of result.modules){const y=Number(module.y_m).toFixed(9);if(!rows.has(y))rows.set(y,[]);rows.get(y).push(module)}let ordered=[];[...rows.keys()].sort((a,b)=>Number(a)-Number(b)).forEach((y,index)=>{const row=rows.get(y).sort((a,b)=>a.x_m-b.x_m);ordered=ordered.concat(snake&&index%2?row.reverse():row)});ordered.forEach((module,index)=>{module.string_id=`STR-${String(Math.floor(index/size)+1).padStart(2,'0')}`;module.electrical_index=index%size+1});return rehash(result)}
