import crypto from 'node:crypto';
export class LayoutError extends Error {}
const finite=(name,value,min=null)=>{const n=Number(value);if(!Number.isFinite(n))throw new LayoutError(`${name} must be finite`);if(min!==null&&n<min)throw new LayoutError(`${name} must be >= ${min}`);return n};
const canonical=value=>JSON.stringify(value,Object.keys(value).sort());
export const layoutHash=value=>`sha256:${crypto.createHash('sha256').update(canonical(value)).digest('hex')}`;
export function footprint(module){let rotation=((Number(module.rotation_deg)||0)%180+180)%180;if(![0,90].includes(rotation))throw new LayoutError('rotation must be 0 or 90 degrees');let width=finite('width_m',module.width_m,.001),height=finite('height_m',module.height_m,.001);if(rotation===90)[width,height]=[height,width];const x=finite('x_m',module.x_m),y=finite('y_m',module.y_m);return{left:x-width/2,right:x+width/2,bottom:y-height/2,top:y+height/2,width,height}}
export const intersects=(a,b)=>Math.min(a.right,b.right)>Math.max(a.left,b.left)&&Math.min(a.top,b.top)>Math.max(a.bottom,b.bottom);
const checkedBoundary=layout=>{const b=Object.fromEntries(['x_min','x_max','y_min','y_max'].map(k=>[k,finite(k,layout.boundary[k])]));if(b.x_max<=b.x_min||b.y_max<=b.y_min)throw new LayoutError('boundary must have positive width and height');return b};
const candidateErrors=(module,boundary,obstacles,existing)=>{const errors=[],fp=footprint(module);if(fp.left<boundary.x_min-1e-12||fp.right>boundary.x_max+1e-12||fp.bottom<boundary.y_min-1e-12||fp.top>boundary.y_max+1e-12)errors.push(`${module.id}: outside boundary`);for(const obstacle of obstacles){const of={left:finite('x_min',obstacle.x_min),right:finite('x_max',obstacle.x_max),bottom:finite('y_min',obstacle.y_min),top:finite('y_max',obstacle.y_max)};if(intersects(fp,of))errors.push(`${module.id}: intersects obstacle ${obstacle.id??'?'}`)}for(const [id,other] of existing)if(intersects(fp,other))errors.push(`${module.id}: overlaps ${id}`);return errors};
export function validateLayout(layout){const errors=[];let boundary;try{boundary=checkedBoundary(layout)}catch(error){return[error.message]}const modules=layout.modules||[],ids=modules.map(module=>module.id),obstacles=layout.obstacles||[],existing=[];if(new Set(ids).size!==ids.length)errors.push('module ids must be unique');for(const module of modules){try{errors.push(...candidateErrors(module,boundary,obstacles,existing));existing.push([module.id,footprint(module)])}catch(error){errors.push(`${module.id||'?'}: ${error.message}`)}}return errors}
const rehash=layout=>{const copy=structuredClone(layout);delete copy.layout_hash;layout.layout_hash=layoutHash(copy);return layout};
export function fillRectangle({boundary,moduleWidthM,moduleHeightM,gapXM=.02,gapYM=.02,orientation='portrait',staggerM=0,obstacles=[],limit=null}){if(!['portrait','landscape'].includes(orientation))throw new LayoutError('orientation must be portrait or landscape');const width=finite('moduleWidthM',moduleWidthM,.001),height=finite('moduleHeightM',moduleHeightM,.001),gapX=finite('gapXM',gapXM,0),gapY=finite('gapYM',gapYM,0),stagger=finite('staggerM',staggerM,0);if(limit!==null&&Number(limit)<0)throw new LayoutError('limit must be non-negative');const rotation=orientation==='landscape'?90:0,[footprintWidth,footprintHeight]=rotation===90?[height,width]:[width,height];const layout={schema_version:'globalgrid2050.v11.module-layout.v1',boundary:{...boundary},obstacles:structuredClone(obstacles),modules:[]},validBoundary=checkedBoundary(layout),accepted=[];let row=0;for(let y=validBoundary.y_min+footprintHeight/2;y+footprintHeight/2<=validBoundary.y_max+1e-12;y+=footprintHeight+gapY,row++){let column=0;for(let x=validBoundary.x_min+footprintWidth/2+(row%2?stagger:0);x+footprintWidth/2<=validBoundary.x_max+1e-12;x+=footprintWidth+gapX,column++){const module={id:`MOD-${String(layout.modules.length+1).padStart(4,'0')}`,x_m:+x.toFixed(9),y_m:+y.toFixed(9),width_m:width,height_m:height,rotation_deg:rotation,row,column,string_id:null};if(candidateErrors(module,validBoundary,layout.obstacles,accepted).length===0){layout.modules.push(module);accepted.push([module.id,footprint(module)]);if(limit!==null&&layout.modules.length>=Number(limit))return rehash(layout)}}}return rehash(layout)}
export function moveModule(layout,id,x,y,snap=.01){const result=structuredClone(layout),target=result.modules.find(module=>module.id===id);if(!target)throw new LayoutError(`unknown module ${id}`);const interval=finite('snap',snap,.000001);target.x_m=+(Math.round(finite('x',x)/interval)*interval).toFixed(9);target.y_m=+(Math.round(finite('y',y)/interval)*interval).toFixed(9);const errors=validateLayout(result);if(errors.length)throw new LayoutError(errors.join('; '));return rehash(result)}
export function rotateModule(layout,id){const result=structuredClone(layout),target=result.modules.find(module=>module.id===id);if(!target)throw new LayoutError(`unknown module ${id}`);target.rotation_deg=(Number(target.rotation_deg)||0)%180===0?90:0;const errors=validateLayout(result);if(errors.length)throw new LayoutError(errors.join('; '));return rehash(result)}
export function assignStrings(layout,size=30,snake=true){if(size<=0)throw new LayoutError('size must be positive');const result=structuredClone(layout),rows=new Map;for(const module of result.modules){const y=Number(module.y_m).toFixed(9);if(!rows.has(y))rows.set(y,[]);rows.get(y).push(module)}let ordered=[];[...rows.keys()].sort((a,b)=>Number(a)-Number(b)).forEach((y,index)=>{const row=rows.get(y).sort((a,b)=>a.x_m-b.x_m);ordered=ordered.concat(snake&&index%2?row.reverse():row)});ordered.forEach((module,index)=>{module.string_id=`STR-${String(Math.floor(index/size)+1).padStart(2,'0')}`;module.electrical_index=index%size+1});return rehash(result)}
