import {fillRectangle,moveModule,rotateModule,assignStrings,footprint,validateLayout} from './layout-core.mjs';
const $=s=>document.querySelector(s);let layout,selected=null,dragging=false;
function inputs(){return{boundary:{x_min:0,y_min:0,x_max:+$('#bw').value,y_max:+$('#bh').value},moduleWidthM:+$('#mw').value,moduleHeightM:+$('#mh').value,gapXM:+$('#gx').value,gapYM:+$('#gy').value,orientation:$('#orientation').value,staggerM:+$('#stagger').value,obstacles:[],limit:720}}
function render(){const svg=$('#canvas'),b=layout.boundary;svg.setAttribute('viewBox',`0 0 ${b.x_max} ${b.y_max}`);svg.innerHTML='';for(const o of layout.obstacles){const r=document.createElementNS('http://www.w3.org/2000/svg','rect');r.setAttribute('x',o.x_min);r.setAttribute('y',b.y_max-o.y_max);r.setAttribute('width',o.x_max-o.x_min);r.setAttribute('height',o.y_max-o.y_min);r.setAttribute('class','obstacle');svg.append(r)}for(const m of layout.modules){const f=footprint(m),r=document.createElementNS('http://www.w3.org/2000/svg','rect');r.setAttribute('x',f.left);r.setAttribute('y',b.y_max-f.top);r.setAttribute('width',f.width);r.setAttribute('height',f.height);r.dataset.id=m.id;r.setAttribute('class',`module${selected===m.id?' selected':''}`);svg.append(r)}$('#status').textContent=`${layout.modules.length} modules · ${new Set(layout.modules.map(m=>m.string_id).filter(Boolean)).size} strings · ${validateLayout(layout).length} errors`}
function rebuild(){try{const filled=fillRectangle(inputs());if(filled.modules.length!==720)throw new Error(`Boundary fits only ${filled.modules.length} modules; 720 required`);layout=assignStrings(filled,30,true);selected=null;render()}catch(error){$('#status').textContent=error.message}}
function pointerToWorld(event){const svg=$('#canvas'),matrix=svg.getScreenCTM();if(!matrix)throw new Error('Layout canvas is not available');const pt=svg.createSVGPoint();pt.x=event.clientX;pt.y=event.clientY;const p=pt.matrixTransform(matrix.inverse());return{x:p.x,y:layout.boundary.y_max-p.y}}
$('#canvas').addEventListener('pointerdown',e=>{const id=e.target.dataset.id;if(!id)return;selected=id;dragging=true;e.target.setPointerCapture(e.pointerId);render()});
$('#canvas').addEventListener('pointermove',e=>{if(!dragging||!selected)return;const p=pointerToWorld(e);try{layout=moveModule(layout,selected,p.x,p.y,.05)}catch(error){$('#status').textContent=error.message}render()});
$('#canvas').addEventListener('pointerup',()=>dragging=false);$('#canvas').addEventListener('pointercancel',()=>dragging=false);
$('#fill').onclick=rebuild;$('#rotate').onclick=()=>{if(selected){try{layout=rotateModule(layout,selected);render()}catch(e){$('#status').textContent=e.message}}};$('#strings').onclick=()=>{layout=assignStrings(layout,30,true);render()};$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(layout,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='v11-module-layout.json';a.click();URL.revokeObjectURL(a.href)};rebuild();
